#!/bin/bash
sites=( cmh zhh mrc allsites )
for site in ${sites[@]}; do

    filename='run-glm_IMOB_'${site}'.sh'
    nsubjpergroup=$(cat list_im-h-${site}.csv | wc -l)
    # set up the analysis
    echo '3dANOVA3 -type 5 -alevels 2 -blevels 2 -clevels '${nsubjpergroup}' \' > ${filename}

    # add healthy subjects
    count=1
    while read line; do 
        echo '    -dset 1 1 '${count} ${line}'_01_IM.nii.gz[67] \' >> ${filename}
        echo '    -dset 1 2 '${count} ${line}'_01_OB.nii.gz[67] \' >> ${filename}
        count=$((count+1))
    done < list_im-h-${site}.csv

    # add schizophrenia subjects
    count=1
    while read line; do 
        echo '    -dset 2 1 '${count} ${line}'_01_IM.nii.gz[67] \' >> ${filename}
        echo '    -dset 2 2 '${count} ${line}'_01_OB.nii.gz[67] \' >> ${filename}
        count=$((count+1))
    done < list_im-p-${site}.csv

    # finish off the analysis
    echo '-fa group -fb cond -fab groupXcond \' >> ${filename}
    echo '-acontr 1 0 HC -acontr 0 1 SC -bcontr 1 0 IM -bcontr 0 1 OB \' >> ${filename}
    echo '-acontr 1 -1 HCvsSC -bcontr 1 -1 IMvsOB \' >> ${filename}
    echo '-Abcontr 1 : 1 -1 IMvsOB_HC -Abcontr 2 : 1 -1 IMvsOB_SC \' >> ${filename}
    echo '-bucket ANOVA-'${site}'.nii.gz' >> ${filename}

    chmod 755 ${filename}
done
